SELECT * FROM Equipment;
SELECT * FROM Aircraft;
SELECT * FROM Hellicopter;
SELECT * FROM Plane;
SELECT * FROM Pilot;
SELECT * FROM Squadron;
SELECT * FROM FuelStock;
SELECT * FROM FuelType;
SELECT * FROM Equipped_With;